'use client';
import Link from 'next/link';
import {EvidenceFlow} from './evidence-flow';
import type {Summary} from '@/lib/types';
import {useScan} from './use-scan';
import {Age,Badge,Countdown,LifeState,ScanButton,shortHash,Source,date} from './primitives';
export function Dashboard({initialData}:{initialData:Summary}){
 const {data,loading,error,refresh}=useScan<Summary>('/api/scan',initialData);
 const assets=data?.assets??[];
 const onchain=assets.flatMap(a=>a.checks.filter(c=>c.bucket==='ONCHAIN VERIFIED'));
 const space=assets.find(a=>a.symbol==='SPACEX'),xai=assets.find(a=>a.symbol==='XAI');
 return <>
 <div className="page-heading"><div><div className="eyebrow"><span className="rust">01 /</span> PRESTOCKS OBSERVATORY</div><h1>Evidence, in the open.</h1><p>Onchain facts vs issuer claims. Not proof of SPV shares.</p></div><div className="scan-controls"><div className="last-scan"><span>LAST SCAN</span><strong>{data?date(data.scannedAt):'NO DATA'}</strong></div><ScanButton loading={loading} onClick={refresh}/></div></div>
 {error&&<div className="error" role="alert">{error} {data?'Showing the previous scan; see its timestamp.':''}<button onClick={refresh}>RETRY ↗</button></div>}
 <div className="metrics" aria-label="Scan totals"><Metric value={data?String(assets.length):'—'} label="ASSETS" note="PreStocks monitored"/><Metric value={data?`${onchain.filter(c=>!c.attention).length}`:'—'} suffix={data?` / ${onchain.length}`:undefined} label="ONCHAIN CHECKS" note="Without triggered conditions"/><Metric value={data?String(assets.filter(a=>a.changed).length):'—'} label="CHANGED" note="Since previous snapshot"/><Metric value={data?String(assets.filter(a=>a.lifecycle.state!=='NONE_ON_FILE').length):'—'} label="ACTION REQUIRED" note="Includes closed windows" accent/></div>
 <section className="registry"><div className="section-top"><h2><span className="section-index">01</span> ASSET REGISTER</h2><div className="meta">{loading?'OBSERVING SOURCES…':'LIVE SOURCE SCANS'}<span className="divider">/</span> AUTO REFRESH 60S</div></div>
 <div className="table-scroll"><table className="asset-table"><thead><tr><th>SYMBOL</th><th>CHECKS <span className="subtle">¹</span></th><th>STATE</th><th>LIFECYCLE</th><th>SHA-256</th><th>AGE</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{!data?<tr><td colSpan={7} className="loading-row">{loading?'Retrieving issuer, Solana and Jupiter evidence…':'NO DATA — scan unavailable'}</td></tr>:assets.map(a=><tr key={a.symbol} className={a.state==='CRITICAL'?'critical-row':''}><td><Link href={`/c/${a.symbol}`} className="asset-name"><span className={`asset-emblem ${a.symbol.toLowerCase()}`}>{a.symbol==='OPENAI'?'O':a.symbol==='ANTHROPIC'?'A':a.symbol==='SPACEX'?'S':'X'}</span><span><strong>{a.symbol}</strong><small>{a.symbol==='XAI'?'HISTORICAL ASSET':'PRESTOCKS'}</small></span></Link></td><td><div className="check-count">{a.checks.filter(c=>!c.attention).length}<span> / {a.checks.length}</span></div><div className="check-ticks" aria-hidden="true">{a.checks.map(c=><i key={c.id} className={c.attention?'flagged':''}/>)}</div></td><td><Badge value={a.state}/>{a.changed&&a.state!=='CHANGED'&&<small className="changed-note">+ STATE CHANGED</small>}</td><td className={a.lifecycle.state==='WINDOW_CLOSED'?'rust':'mono'}><LifeState life={a.lifecycle} at={a.scannedAt}/></td><td><Link className="hash-link" href={`/c/${a.symbol}#history`} title={a.currentHash}>{shortHash(a.currentHash)}</Link></td><td className="mono muted"><Age at={a.scannedAt} initialAge={a.age}/></td><td><Link href={`/c/${a.symbol}`} className="row-arrow" aria-label={`View ${a.symbol} evidence`}>↗</Link></td></tr>)}</tbody></table></div><div className="table-note"><span>¹ Checks without triggered conditions / total checks. This is not a risk score.</span><span>4 EVIDENCE LAYERS · NO LLM SCORING</span></div></section>
 <EvidenceFlow loading={loading} scannedAt={data?.scannedAt} hash={data?.hash} checks={assets.flatMap(a=>a.checks)} assetCount={assets.length} persistence={data?.persistence} error={error}/>
 <section className="lifecycle-overview"><div className="section-top"><h2><span className="section-index">02</span> LIFECYCLE WATCH</h2><span className="meta">ISSUER DISCLOSURES · MANUALLY VERIFIED</span></div><div className="watch-grid"><article className="watch closed"><div className="watch-top"><span className="eyebrow">XAI → SPACEX</span><Badge value="WINDOW_CLOSED"/></div><h3>A token can outlive its terms.</h3><p>PreStocks’ XAI conversion window has closed. The mint’s existence does not establish that its economic lifecycle remains active.</p><div className="watch-data"><div><span>ISSUER CONVERSION</span><strong>1 XAI → 0.7165 SPACEX</strong></div><div><span>MINT OBSERVABLE</span><strong>{xai?.mintObservable??'NO DATA'}</strong></div></div><Link href="/c/XAI" className="text-link">INSPECT XAI EVIDENCE <span>↗</span></Link></article><article className="watch upcoming"><div className="watch-top"><span className="eyebrow">SPACEX / PUBLIC TRANSITION</span><Badge value={space?.lifecycle.state??'ACTION'}/></div><div className="countdown-display"><Countdown deadline="2027-03-12T23:59:00Z" at={space?.scannedAt}/ ></div><p>Issuer requires conversion into <strong>$SPCXx or any other token</strong> before 12 March 2027, 23:59 UTC.</p><div className="watch-data"><div><span>EVIDENCE REVIEWED</span><strong>21 SEP 2026</strong></div><Source url="https://prestocks.com/spacex">PRESTOCKS</Source></div><Link href="/c/SPACEX" className="text-link">REVIEW HOLDER ACTION <span>↗</span></Link></article></div></section>
 <section className="evidence-guide"><div className="section-top"><h2><span className="section-index">03</span> READ THE EVIDENCE</h2><span className="meta">DIFFERENT SOURCES. DIFFERENT CLAIMS.</span></div><div className="evidence-grid"><div><span className="evidence-number">[ A ]</span><h3>ONCHAIN VERIFIED</h3><p>Mint state, authorities and supply observed directly from Solana.</p></div><div><span className="evidence-number">[ B ]</span><h3>ISSUER / THIRD PARTY</h3><p>Reference marks, lifecycle terms and dated attestation reports. Sources attached.</p></div><div><span className="evidence-number">[ C ]</span><h3>MARKET OBSERVED</h3><p>Reported token prices and a measured $500 Jupiter route. A moment in time.</p></div><div><span className="evidence-number rust">[ D ]</span><h3>NOT INDEPENDENTLY<br/>OBSERVABLE</h3><p>Private cap tables and current custody beyond the published evidence.</p></div></div></section>
 <div className="system-line"><span>SNAPSHOT STORAGE <b>{data?.persistence??'NO DATA'}</b></span><span>PUBLIC EVIDENCE. EXPLICIT LIMITS.</span></div>
 </>;
}
function Metric({value,suffix,label,note,accent=false}:{value:string;suffix?:string;label:string;note:string;accent?:boolean}){return <div className={`metric ${accent?'accent':''}`}><span>{label}</span><div>{value}<small>{suffix}</small></div><p>{note}</p></div>;}
