'use client';
import Link from 'next/link';
import {EvidenceFlow} from './evidence-flow';
import type {Summary} from '@/lib/types';
import {useScan} from './use-scan';
import {Age,AssetEmblem,Badge,Countdown,LifeState,ScanButton,shortHash,Source,date} from './primitives';
export function Dashboard({initialData}:{initialData:Summary}){
 const {data,loading,error,refresh}=useScan<Summary>('/api/scan',initialData);
 const assets=data?.assets??[];
 const onchain=assets.flatMap(a=>a.checks.filter(c=>c.bucket==='ONCHAIN VERIFIED'));
 const space=assets.find(a=>a.symbol==='SPACEX'),xai=assets.find(a=>a.symbol==='XAI');
 return <>
 <div className="page-heading"><div><div className="eyebrow"><span className="rust">01 /</span> PRESTOCKS OBSERVATORY</div><h1>Know when your private-market token changes.</h1><p className="lede">Parity monitors PreStocks across Solana state, issuer disclosures, market observations, and lifecycle deadlines.</p><p className="honesty"><strong>Onchain facts vs issuer claims. Not proof of SPV shares.</strong></p></div><div className="scan-controls"><div className="last-scan"><span>LAST SCAN</span><strong>{data?date(data.scannedAt):'NO DATA'}</strong></div><ScanButton loading={loading} onClick={refresh}/></div></div>
 {error&&<div className="error" role="alert">{error} {data?'Showing the previous scan; see its timestamp.':''}<button onClick={refresh}>RETRY ↗</button></div>}
 <div className="metrics" aria-label="Scan totals"><Metric value={data?String(assets.length):','} label="ASSETS" note="PreStocks monitored"/><Metric value={data?`${onchain.filter(c=>!c.attention).length}`:','} suffix={data?` / ${onchain.length}`:undefined} label="CLEAR CHECKS" note="Onchain, across monitored assets"/><Metric value={data?String(assets.filter(a=>a.state==='ATTENTION').length):','} label="ATTENTION" note="A monitoring threshold is triggered"/><Metric value={data?String(assets.filter(a=>a.lifecycle.state!=='NONE_ON_FILE').length):','} label="ACTION REQUIRED" note="Includes closed windows" accent/></div>
 <section className="registry"><div className="section-top"><h2><span className="section-index">01</span> ASSET REGISTER</h2><div className="meta">{loading?'OBSERVING SOURCES…':'LIVE SOURCE SCANS'}<span className="divider">/</span> AUTO REFRESH 60S</div></div>
 <div className="table-scroll"><table className="asset-table"><thead><tr><th>SYMBOL</th><th>CHECKS <span className="subtle">¹</span></th><th>STATE</th><th>LIFECYCLE</th><th>INTEGRITY HASH</th><th>AGE</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{!data?<tr><td colSpan={7} className="loading-row">{loading?'Retrieving issuer, Solana and Jupiter evidence…':'NO DATA, scan unavailable'}</td></tr>:assets.map(a=><tr key={a.symbol} className={a.state==='CRITICAL'?'critical-row':''}><td><Link href={`/c/${a.symbol}`} className="asset-name"><AssetEmblem symbol={a.symbol}/><span><strong>{a.symbol}</strong><small>{a.symbol==='XAI'?'HISTORICAL ASSET':'PRESTOCKS'}</small></span></Link></td><td><div className="check-count">{a.checks.filter(c=>!c.attention).length}<span> / {a.checks.length}</span></div><div className="check-ticks" aria-hidden="true">{a.checks.map(c=><i key={c.id} className={c.attention?'flagged':''}/>)}</div></td><td><Badge value={a.state}/></td><td className={a.lifecycle.state==='WINDOW_CLOSED'?'rust':'mono'}><LifeState life={a.lifecycle} at={a.scannedAt}/></td><td><Link className="hash-link" href={`/c/${a.symbol}#history`} title={a.currentHash}>{shortHash(a.currentHash)}</Link></td><td className="mono muted"><Age at={a.scannedAt} initialAge={a.age}/></td><td><Link href={`/c/${a.symbol}`} className="row-arrow" aria-label={`View ${a.symbol} evidence`}>↗</Link></td></tr>)}</tbody></table></div><div className="table-note"><span>¹ Checks without triggered conditions / total checks. This is not a risk score.</span><span>4 EVIDENCE LAYERS · NO LLM SCORING</span></div></section>
 <EvidenceFlow loading={loading} scannedAt={data?.scannedAt} hash={data?.hash} checks={assets.flatMap(a=>a.checks)} assetCount={assets.length} persistence={data?.persistence} error={error}/>
 <section className="lifecycle-overview"><div className="section-top"><h2><span className="section-index">02</span> LIFECYCLE WATCH</h2><span className="meta">ISSUER DISCLOSURES · MANUALLY VERIFIED</span></div><div className="watch-grid"><article className="watch closed"><div className="watch-top"><span className="eyebrow">XAI → SPACEX</span><Badge value="WINDOW_CLOSED"/></div><h3>A token can outlive its terms.</h3><p>PreStocks’ XAI conversion window has closed. The mint’s existence does not establish that its economic lifecycle remains active.</p><div className="xai-split"><div><span>ONCHAIN</span><strong>Mint remains observable.</strong></div><div><span>ISSUER DISCLOSURE</span><strong>Conversion window closed.</strong></div></div><p className="xai-why"><strong>Why this matters:</strong> a token can remain observable onchain after its issuer-defined economic window has ended.</p><div className="watch-data"><div><span>ISSUER CONVERSION</span><strong>1 XAI → 0.7165 SPACEX</strong></div><div><span>MINT OBSERVABLE</span><strong>{xai?.mintObservable??'NO DATA'}</strong></div></div><Link href="/c/XAI" className="text-link">INSPECT XAI EVIDENCE <span>↗</span></Link></article><article className="watch upcoming"><div className="watch-top"><span className="eyebrow">SPACEX / PUBLIC TRANSITION</span><Badge value={space?.lifecycle.state??'ACTION'}/></div><div className="countdown-display"><Countdown deadline="2027-03-12T23:59:00Z" at={space?.scannedAt}/ ></div><p>Issuer requires conversion into <strong>$SPCXx or any other token</strong> before 12 March 2027, 23:59 UTC.</p><div className="watch-data"><div><span>EVIDENCE REVIEWED</span><strong>21 SEP 2026</strong></div><Source url="https://prestocks.com/spacex">PRESTOCKS</Source></div><Link href="/c/SPACEX" className="text-link">REVIEW HOLDER ACTION <span>↗</span></Link></article></div></section>
 <section className="why-parity"><div className="section-top"><h2><span className="section-index">02B</span> WHY PARITY?</h2></div><p>A PreStock crosses several trust boundaries:</p><ol className="trust-chain" aria-label="Trust boundaries"><li>PRIVATE COMPANY</li><li>SPV / ISSUER</li><li>PRESTOCK</li><li>SOLANA TOKEN</li><li>HOLDER</li></ol><p>Solana can prove the token state. Issuer disclosures describe the offchain economic lifecycle. Parity monitors both without pretending they are the same evidence.</p></section>
 <section className="evidence-guide"><div className="section-top"><h2><span className="section-index">03</span> READ THE EVIDENCE</h2><span className="meta">DIFFERENT SOURCES. DIFFERENT CLAIMS.</span></div><div className="evidence-grid"><div className="layer-a"><span className="evidence-number">[ A ]</span><h3>ONCHAIN VERIFIED</h3><p>Independently observed from Solana. Mint, authorities, supply, Token-2022.</p></div><div className="layer-b"><span className="evidence-number">[ B ]</span><h3>ISSUER ATTESTED</h3><p>Sourced from PreStocks or another identified provider.</p></div><div className="layer-c"><span className="evidence-number">[ C ]</span><h3>MARKET OBSERVED</h3><p>Token price, premium, and Jupiter routing. A moment in time.</p></div><div className="layer-d"><span className="evidence-number">[ D ]</span><h3>NOT INDEPENDENTLY<br/>OBSERVABLE</h3><p>Information Parity cannot establish independently from currently available evidence.</p></div></div></section>
 <div className="system-line"><span>SNAPSHOT STORAGE <b>{data?.persistence??'NO DATA'}</b></span><span>PUBLIC EVIDENCE. EXPLICIT LIMITS.</span></div>
 </>;
}
function Metric({value,suffix,label,note,accent=false}:{value:string;suffix?:string;label:string;note:string;accent?:boolean}){return <div className={`metric ${accent?'accent':''}`}><span>{label}</span><div>{value}<small>{suffix}</small></div><p>{note}</p></div>;}
