'use client';
import Link from 'next/link';
import {EvidenceFlow} from './evidence-flow';
import type {Detail as DetailData, SymbolName, Json} from '@/lib/types';
import { MARKET_LIMITATION, FAQ_URL } from '@/data/lifecycle';
import {useScan} from './use-scan';
import {Age,Badge,Countdown,ScanButton,Source,Value,amount,date,money,shortHash} from './primitives';
function Datum({label,children}:{label:string;children:React.ReactNode}){return <div className="datum"><dt>{label}</dt><dd>{children}</dd></div>;}
function SectionTitle({index,title,label}:{index:string;title:string;label?:string}){return <div className="section-top"><h2><span className="section-index">{index}</span>{title}</h2>{label&&<span className="meta">{label}</span>}</div>;}
export function Detail({symbol}:{symbol:SymbolName}){
 const {data:s,loading,error,refresh}=useScan<DetailData>(`/api/scan/${symbol}`);
 return <><nav className="breadcrumb"><Link href="/">ASSET REGISTER</Link><span>/</span><span>{symbol}</span></nav><div className="detail-heading"><div><div className="eyebrow">PRESTOCKS / EVIDENCE DOSSIER</div><div className="detail-title-line"><h1>{symbol}</h1>{s&&<Badge value={s.state}/>}</div><div className="detail-meta"><span>LAST OBSERVED {s?<Age at={s.scannedAt}/>:'NO DATA'}</span><span>SHA-256 {s?shortHash(s.currentHash):'—'}</span>{s?.changed&&<span className="rust">{s.changedFields.length} CHANGED FIELDS</span>}</div></div><ScanButton loading={loading} onClick={refresh}/></div>
 {error&&<div className="error" role="alert">{error} {s?'Previous scan retained; see its timestamp.':''}<button onClick={refresh}>RETRY ↗</button></div>}
 {!s?<div className="loading-row" role="status">{loading?'Observing Solana, issuer evidence and the $500 market route…':'NO DATA'}</div>:<>
 {s.errors.length>0&&<div className="error" role="status">{s.errors.map(e=>`${e.source}: ${e.message}`).join(' ')}</div>}
 <EvidenceFlow loading={loading} scannedAt={s.scannedAt} hash={s.currentHash} checks={s.checks} assetCount={1} persistence={s.persistence} error={error}/>
 <nav className="evidence-tabs" aria-label="Evidence sections"><a href="#onchain">A / ONCHAIN</a><a href="#issuer">B / ISSUER EVIDENCE</a><a href="#market">C / MARKET</a><a href="#limits">D / LIMITS</a><a href="#history">HISTORY ↓</a></nav>
 {s.lifecycle.deadline&&<section className="detail-life"><div className="life-main"><div className="eyebrow rust">LIFECYCLE / ISSUER ATTESTED</div><h2>{s.lifecycle.event==='ACQUIRED'?'xAI → SpaceX':'SpaceX · public-company transition'}</h2><Badge value={s.lifecycle.state}/><dl className="life-facts"><Datum label={symbol==='XAI'?'ISSUER CONVERSION':'TARGET IN ISSUER DISCLOSURE'}>{s.lifecycle.ratio?`1 XAI → ${s.lifecycle.ratio} SPACEX`:s.lifecycle.target}</Datum><Datum label="DEADLINE">{date(s.lifecycle.deadline)}</Datum><Datum label="ISSUER-STATED CONSEQUENCE">{s.lifecycle.consequence}</Datum><Datum label="EVIDENCE"><Source url={s.lifecycle.sourceUrl}>PRESTOCKS DISCLOSURE</Source><p className="scan-note">Reviewed {s.lifecycle.verifiedAt}</p></Datum></dl></div><div className="life-aside"><div className="eyebrow">{s.lifecycle.state==='WINDOW_CLOSED'?'CONVERSION STATUS':'ACTION REQUIRED'}</div><div className="big-state"><Countdown deadline={s.lifecycle.deadline}/></div>{s.lifecycle.state==='ACTION'&&<p>{s.lifecycle.action}</p>}<div className="eyebrow">ONCHAIN STATUS</div><p>Mint remains observable: <strong className="mono">{s.mintObservable}</strong></p><p>The existence of an onchain mint does not establish that its economic lifecycle remains active.</p></div></section>}
 <section id="onchain"><SectionTitle index="A" title="ONCHAIN VERIFIED" label={`FINALIZED · SLOT ${s.observations.rpcSlot??'NO DATA'}`}/><p className="section-description">Facts observed from Solana. Authority presence is recorded explicitly; a freeze authority triggers attention.</p><div className="table-scroll"><table className="asset-table checks-table"><thead><tr><th>CHECK</th><th>EXPECTED / PREVIOUS</th><th>CURRENT</th><th>FIRST SEEN</th><th>STATUS</th></tr></thead><tbody>{s.checks.filter(c=>c.bucket==='ONCHAIN VERIFIED').map(c=><tr key={c.id}><td>{c.label}<small><Source url={c.sourceUrl}>EVIDENCE</Source></small></td><td><Value value={c.expected}/></td><td>{(c.id==='mintAuthority'||c.id==='freezeAuthority')&&s.mint&&c.current===null?<span>NONE · REVOKED</span>:<Value value={c.current}/>}</td><td>{date(c.firstSeen)}</td><td><Badge value={c.status}/></td></tr>)}</tbody></table></div>
 <div className="mint-detail"><div><dl><Datum label="TOKEN PROGRAM">{s.mint?.program??'NO DATA'}</Datum></dl><code className="json-value">{s.mint?.owner??'NO DATA'}</code></div><div><dl><Datum label="ONCHAIN METADATA">{s.mint?.metadata?`${s.mint.metadata.name??'NO DATA'} / ${s.mint.metadata.symbol??'NO DATA'}`:'NO DATA'}</Datum></dl>{typeof s.mint?.metadata?.uri==='string'&&<Source url={s.mint.metadata.uri}>METADATA URI</Source>}</div><div><dl><Datum label="ADDRESS PROVENANCE">{s.mintSource.replaceAll('_',' ')}</Datum></dl><p className="scan-note">{symbol==='XAI'?'Historical address corroborated by issuer page and onchain metadata. Current catalogue match: NO DATA.':`Current issuer catalogue: ${s.catalogueStatus}`}</p></div></div>
 <details className="details-box"><summary>TOKEN EXTENSIONS & SCALED UI CONFIGURATION ↓</summary><p className="section-description" style={{marginTop:16}}>Base UI supply is raw supply ÷ 10^decimals. Scaled UI supply applies the effective Token-2022 multiplier separately. Neither establishes underlying holdings.</p><Value value={s.mint?.extensions as unknown as Json??null}/></details></section>
 <section id="issuer"><SectionTitle index="B" title="ISSUER / THIRD-PARTY EVIDENCE" label="CLAIMS RETAIN THEIR PROVENANCE"/><div className="issuer-grid"><article className="issuer-panel"><Badge value="ISSUER ATTESTED"/><h3>Reference mark & issuer terms</h3><dl><Datum label="MARK PRICE">{money(s.catalogue?.markPrice)}</Datum><Datum label="MARK VALUATION">{money(s.catalogue?.markValuation)}</Datum><Datum label="API PULLED AT">{date(s.observations.cataloguePulledAt)}</Datum><Datum label="MARK UPDATED AT">{s.catalogue?.markUpdatedAt??'NO DATA'}</Datum><Datum label="ISSUER-REPORTED SUPPLY">{amount(s.catalogue?.supply)}</Datum><Datum label="LIFECYCLE ON FILE"><Badge value={s.lifecycle.state}/></Datum></dl><p>API retrieval time does not establish when the issuer’s mark was last updated.</p><Source url="https://prestocks.com/api/prestocks">PRESTOCKS API</Source><span> · </span><Source url={s.lifecycle.sourceUrl}>PRODUCT DISCLOSURE</Source>{s.lifecycle.state==='NONE_ON_FILE'&&<p>No lifecycle action found in the reviewed product disclosure as of {s.lifecycle.verifiedAt}. This is not proof that no event exists.</p>}</article>
 <article className="issuer-panel"><Badge value={s.attestation?'THIRD-PARTY ATTESTED':'NO DATA'}/><h3>{s.attestation?'Published backing attestation':'Backing report not on file'}</h3>{s.attestation?<><dl><Datum label="ATTESTING ENTITY">{s.attestation.provider}</Datum><Datum label="REPORT DATE">{s.attestation.reportDate}</Datum><Datum label="REPORTED MINTABLE SUPPLY">{s.attestation.mintableSupply}</Datum><Datum label="REPORTED MINTED SUPPLY">{s.attestation.mintedSupply}</Datum></dl><p>{s.attestation.scope}</p><p>The report attests that reported minted supply is covered by reported mintable supply. These dated figures are not current onchain supply.</p><Source url={s.attestation.sourceUrl}>READ ATTESTATION</Source></>:<><p>No linked report was found on this asset’s product page during the {s.lifecycle.verifiedAt} review. This does not establish that no report exists.</p><p>PreStocks says reports are published periodically or available on request, potentially with costs covered by the requester.</p></>}<p><Source url={FAQ_URL}>ISSUER’S VERIFICATION EXPLANATION</Source></p></article></div></section>
 <section id="market"><SectionTitle index="C" title="MARKET OBSERVED" label="OBSERVATIONS, NOT RECOMMENDATIONS"/><div className="market-grid"><div><dt>TOKEN PRICE</dt><dd>{money(s.catalogue?.tokenPrice)}</dd><small>Reported by PreStocks API</small></div><div><dt>REFERENCE MARK</dt><dd>{money(s.catalogue?.markPrice)}</dd><small>Issuer-attested reference</small></div><div><dt>MARK / TOKEN PREMIUM</dt><dd className={s.premium!==null&&Math.abs(s.premium)>.15?'rust':''}>{s.premium===null?'NO DATA':`${s.premium>=0?'+':''}${(s.premium*100).toFixed(2)}%`}</dd><small>{s.premium===null?'NO DATA':`${(s.premium*10000).toFixed(1)} BPS`} · threshold ±15%</small></div><div><dt>IMPLIED VALUATION</dt><dd style={{fontSize:17}}>{money(s.catalogue?.impliedValuation)}</dd><small>Reported by PreStocks API</small></div></div>
 <div className="quote-panel"><div className="quote-top"><h3>JUPITER / $500 USDC OBSERVATION</h3><Badge value={s.checks.find(c=>c.id==='jupiter')?.status??'NO DATA'}/></div><dl className="quote-fields"><Datum label="ROUTE EXISTS">{s.quote?.routeExists??'NO DATA'}</Datum><Datum label="OUTPUT AMOUNT · RAW">{s.quote?.outAmount??'NO DATA'}</Datum><Datum label="PRICE IMPACT">{s.quote?.priceImpactPct!==null&&s.quote?.priceImpactPct!==undefined?`${(Number(s.quote.priceImpactPct)*100).toFixed(3)}%`:'NO DATA'}</Datum><Datum label="INPUT AMOUNT · RAW USDC">500000000</Datum><Datum label="QUOTE OBSERVED AT">{date(s.observations.quotePulledAt)}</Datum><Datum label="EVIDENCE"><Source url={s.quote?.sourceUrl??'https://lite-api.jup.ag/swap/v1/quote'}>QUOTE REQUEST</Source></Datum></dl><details className="details-box"><summary>ROUTE DETAILS / ERROR BODY ↓</summary><Value value={s.quote?s.quote.error??s.quote.routePlan:null}/></details><p className="limitation">{MARKET_LIMITATION} Quotes cover observed permissionless Solana DEX routing only. No transaction is executed.</p><p className="scan-note"><Source url="https://prestocks.com/api/prestocks">PRICE & VALUATION SOURCE</Source></p></div></section>
 <section id="limits"><SectionTitle index="D" title="NOT INDEPENDENTLY OBSERVABLE"/><div className="unobservable"><div><div className="eyebrow">THE EVIDENCE BOUNDARY</div><h3>Beyond the public record.</h3><strong>DO NOT CONFUSE WITH ONCHAIN TOKEN SUPPLY.</strong></div><div><p>Parity cannot independently establish current SPV share custody, the exact private-company cap table, or confidential holding-entity identities from the public evidence reviewed.</p><p>Published third-party attestations are meaningful, dated evidence of their stated scope. They do not expose a live custody record or let Parity reproduce the underlying document review.</p><Source url={FAQ_URL}>PRESTOCKS BACKING & CONFIDENTIALITY FAQ</Source></div></div></section>
 <section id="history"><SectionTitle index="04" title="PARITY HISTORY" label="CANONICAL JSON / SHA-256"/><p className="section-description">Up to 100 real scans. Open a row to inspect its recorded differences. Observation clocks are excluded from the state hash.</p><div className="full-hashes"><dl><Datum label="CURRENT HASH">{s.currentHash}</Datum></dl><dl><Datum label="PREVIOUS HASH">{s.previousHash??'FIRST SEEN — NO PREVIOUS SNAPSHOT'}</Datum></dl></div><div className="history-list">{s.history.map((h,index)=><details className="history-entry" key={`${h.scannedAt}-${index}`}><summary><span>{date(h.scannedAt)}</span><span className="muted">{shortHash(h.currentHash)}</span><Badge value={h.changed?'CHANGED':h.state}/><span>{h.changedFields.length>0?`${h.changedFields.length} FIELDS ↓`:h.previousHash?'UNCHANGED ↓':'FIRST SEEN ↓'}</span></summary><div className="history-diffs"><h3>WHAT CHANGED</h3>{h.changedFields.length===0?<p className="section-description">{h.previousHash?'No state-bearing fields changed.':'First observation. No previous snapshot exists for comparison.'}</p>:h.changedFields.map(d=><div className="diff-row" key={d.field}><span>{d.field}</span><Value value={d.previous}/><span>→</span><Value value={d.current}/></div>)}</div></details>)}</div><details className="details-box"><summary>INSPECT CANONICAL SNAPSHOT ↓</summary><Value value={s.canonical}/></details><p className="scan-note">Storage: {s.persistence}. Refresh interval: 60 seconds while visible. Minimum scan interval: 30 seconds.</p>{s.persistence.startsWith('UNAVAILABLE')&&<p className="storage-warning">Durable history is unavailable. This observation is not saved.</p>}</section>
 <div className="system-line"><span>SCAN {date(s.scannedAt)}</span><Source url={`/api/scan/${symbol}`}>API</Source></div>
 </> }</>;
}
